# wescene-renderer — Wallpaper Engine scene (.pkg) renderer for waywallen.

[renderer]
name = "wescene-renderer"
bin  = "../../../bin/waywallen-wescene-renderer"
types = ["scene"]
priority = 100
spawn_version = 4
extras = ["assets", "workshop_id"]
events = ["pointer"]

[renderer.settings]
enable_audio = { type = "bool", default = true, identity = true, label_key = "Habilitar Audio", group = "audio", order = 5 }
volume = { type = "u32", default = 100, min = 0, max = 100, step = 1, identity = false, label_key = "Volumen", group = "audio", order = 10 }
fps    = { type = "u32", default = 30,  min = 1, max = 240, step = 1, identity = false, label_key = "Límite de FPS", group = "render", order = 20 }
render_node = { type = "string", default = "", identity = true, label_key = "Tarjeta Gráfica (Render Node)", group = "render", order = 30 }
